name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "Regex"
path = "../"

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic"
rev = "f8c99ff779ec217063545b3b191747c92e7fbfb3"

[[require]]
scope = "leanprover"
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.30.0"
